module.exports.categoryService = require('./category.service')
module.exports.subCategoryService = require('./subcategory.service')
module.exports.productService = require('./product.service')
module.exports.variantService = require('./variant.service')
module.exports.userService = require('./users.service')