module.exports.categoryValidation = require('./category.validation')
module.exports.subCategoryValidation = require('./subcategory.validation')
module.exports.productValidation = require('./product.validation')
module.exports.variantValidation = require('./variant.validation')
module.exports.UserValidation = require('./users.validation')