module.exports.categoryController = require('./category.controller')
module.exports.subCategoryController = require('./subcategory.contoller')
module.exports.productController = require('./product.controller')
module.exports.variantController = require('./variant.controller')
module.exports.userController = require('./users.controller')